let propertyList = [
  {
    id: 1,
    title: "Elegant Equestrian Estate",
    image: "Property7.png",
    size: 2053,
    rent: 1789.15,
    bedrooms: 7,
    bathrooms: 9,
    neighbourhood: "Glenbrook",
    propertyType: "Apartment",
    landlord: "landtest",
  },
  {
    id: 2,
    title: "Elegant Downtown Penthouse",
    image: "Property18.png",
    size: 1663,
    rent: 820.47,
    bedrooms: 1,
    bathrooms: 4,
    neighbourhood: "Killarney",
    propertyType: "Duplex",
    landlord: "landtest",
  },
  {
    id: 3,
    title: "Tropical Paradise Bungalow",
    image: "Property6.png",
    size: 504,
    rent: 2605.16,
    bedrooms: 6,
    bathrooms: 8,
    neighbourhood: "Cedarbrae",
    propertyType: "House",
    landlord: "resaLmother@email.com",
  },
  {
    id: 4,
    title: "Seaside Spanish Villa",
    image: "Property4.png",
    size: 304,
    rent: 2818.04,
    bedrooms: 9,
    bathrooms: 6,
    neighbourhood: "Pump Hill",
    propertyType: "Room",
    landlord: "landtest",
  },
  {
    id: 5,
    title: "Countryside Castle Cottage",
    image: "Property16.png",
    size: 333,
    rent: 1609.27,
    bedrooms: 5,
    bathrooms: 3,
    neighbourhood: "Elboya",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 6,
    title: "Island Paradise Getaway",
    image: "Property15.png",
    size: 923,
    rent: 1885.08,
    bedrooms: 4,
    bathrooms: 5,
    neighbourhood: "Glendale",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 7,
    title: "Rustic Riverfront Lodge",
    image: "Property11.png",
    size: 1128,
    rent: 2679.97,
    bedrooms: 9,
    bathrooms: 2,
    neighbourhood: "Tuxedo Park",
    propertyType: "House",
    landlord: "landtest",
  },
  {
    id: 8,
    title: "Sleek Skyline View Condo",
    image: "Property7.png",
    size: 717,
    rent: 2617.5,
    bedrooms: 2,
    bathrooms: 8,
    neighbourhood: "Parkdale",
    propertyType: "House",
  },
  {
    id: 9,
    title: "Historic Brownstone in the Heart of the City",
    image: "Property9.png",
    size: 948,
    rent: 1382.11,
    bedrooms: 4,
    bathrooms: 9,
    neighbourhood: "South Calgary",
    propertyType: "Apartment",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 10,
    title: "Cozy Cabin in the Woods",
    image: "Property7.png",
    size: 1009,
    rent: 2192.62,
    bedrooms: 2,
    bathrooms: 6,
    neighbourhood: "Montgomery",
    propertyType: "Apartment",
  },
  {
    id: 11,
    title: "Tree-lined Suburban Sanctuary",
    image: "Property17.png",
    size: 210,
    rent: 953.48,
    bedrooms: 6,
    bathrooms: 7,
    neighbourhood: "Greenwood/Greenbriar",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 12,
    title: "Lakeside Log Cabin",
    image: "Property1.png",
    size: 2278,
    rent: 646.23,
    bedrooms: 6,
    bathrooms: 1,
    neighbourhood: "Acadia",
    propertyType: "Duplex",
  },
  {
    id: 13,
    title: "Serene Seaside Villa",
    image: "Property15.png",
    size: 818,
    rent: 2084.56,
    bedrooms: 9,
    bathrooms: 8,
    neighbourhood: "Acadia",
    propertyType: "House",
  },
  {
    id: 14,
    title: "Tree-lined Suburban Sanctuary",
    image: "Property16.png",
    size: 1297,
    rent: 1574.5,
    bedrooms: 1,
    bathrooms: 4,
    neighbourhood: "Mission",
    propertyType: "Basement",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 15,
    title: "Sunset Beach Bungalow",
    image: "Property14.png",
    size: 1884,
    rent: 480.79,
    bedrooms: 8,
    bathrooms: 7,
    neighbourhood: "Lake Bonavista",
    propertyType: "Basement",
    landlord: "resaLmother@email.com",
  },
  {
    id: 16,
    title: "Modern Lakeside Retreat",
    image: "Property1.png",
    size: 717,
    rent: 852.97,
    bedrooms: 8,
    bathrooms: 6,
    neighbourhood: "Coach Hill",
    propertyType: "Duplex",
    landlord: "landtest",
  },
  {
    id: 17,
    title: "Tropical Treehouse Escape",
    image: "Property17.png",
    size: 1635,
    rent: 330.83,
    bedrooms: 4,
    bathrooms: 1,
    neighbourhood: "Kensington",
    propertyType: "Room",
    landlord: "resaLmother@email.com",
  },
  {
    id: 18,
    title: "Upside Apartment",
    image: "Property10.png",
    size: 2162,
    rent: 980.19,
    bedrooms: 4,
    bathrooms: 1,
    neighbourhood: "Crestmont",
    propertyType: "Apartment",
  },
  {
    id: 19,
    title: "Tropical Treehouse Escape",
    image: "Property7.png",
    size: 554,
    rent: 1981.58,
    bedrooms: 1,
    bathrooms: 6,
    neighbourhood: "Valley Ridge",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 20,
    title: "Mountain Haven Chalet",
    image: "Property17.png",
    size: 2275,
    rent: 1551.51,
    bedrooms: 4,
    bathrooms: 5,
    neighbourhood: "Kensington",
    propertyType: "House",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 21,
    title: "Artsy Loft in the Arts District",
    image: "Property11.png",
    size: 1015,
    rent: 1139.51,
    bedrooms: 3,
    bathrooms: 9,
    neighbourhood: "South Calgary",
    propertyType: "House",
    landlord: "landtest",
  },
  {
    id: 22,
    title: "Secluded Desert Oasis",
    image: "Property10.png",
    size: 1202,
    rent: 2086.1,
    bedrooms: 8,
    bathrooms: 6,
    neighbourhood: "Discovery Ridge",
    propertyType: "Room",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 23,
    title: "Rustic Riverfront Lodge",
    image: "Property7.png",
    size: 2347,
    rent: 1667.42,
    bedrooms: 5,
    bathrooms: 2,
    neighbourhood: "Highland Park",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 24,
    title: "Tranquil Retreat Cottage",
    image: "Property17.png",
    size: 257,
    rent: 196.66,
    bedrooms: 7,
    bathrooms: 2,
    neighbourhood: "Lakeview",
    propertyType: "House",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 25,
    title: "Elegant Equestrian Estate",
    image: "Property15.png",
    size: 1337,
    rent: 2781.2,
    bedrooms: 8,
    bathrooms: 7,
    neighbourhood: "Woodbine",
    propertyType: "Apartment",
    landlord: "resaLmother@email.com",
  },
  {
    id: 26,
    title: "Whimsical Waterfront Yurt",
    image: "Property18.png",
    size: 806,
    rent: 2019.74,
    bedrooms: 4,
    bathrooms: 2,
    neighbourhood: "Lake Bonavista",
    propertyType: "Apartment",
  },
  {
    id: 27,
    title: "Artsy Urban Studio",
    image: "Property6.png",
    size: 1317,
    rent: 1335.95,
    bedrooms: 4,
    bathrooms: 2,
    neighbourhood: "Crescent Heights",
    propertyType: "Room",
    landlord: "landtest",
  },
  {
    id: 28,
    title: "Lakeside Log Cabin",
    image: "Property3.png",
    size: 2253,
    rent: 1657.86,
    bedrooms: 4,
    bathrooms: 3,
    neighbourhood: "Willow Park Estates",
    propertyType: "Basement",
  },
  {
    id: 29,
    title: "Zen Garden Oasis",
    image: "Property17.png",
    size: 1702,
    rent: 2363.87,
    bedrooms: 3,
    bathrooms: 4,
    neighbourhood: "Glenmore Park",
    propertyType: "House",
    landlord: "resaLmother@email.com",
  },
  {
    id: 30,
    title: "Tranquil Tea Garden House",
    image: "Property11.png",
    size: 480,
    rent: 2329.19,
    bedrooms: 7,
    bathrooms: 2,
    neighbourhood: "Rosscarrock",
    propertyType: "Apartment",
    landlord: "resaLmother@email.com",
  },
  {
    id: 31,
    title: "Boho Beachfront Bungalow",
    image: "Property11.png",
    size: 848,
    rent: 1440.35,
    bedrooms: 4,
    bathrooms: 1,
    neighbourhood: "Lakeview",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 32,
    title: "Cozy Coastal Cottage",
    image: "Property3.png",
    size: 2049,
    rent: 1645.96,
    bedrooms: 1,
    bathrooms: 6,
    neighbourhood: "Sunnyside",
    propertyType: "House",
    landlord: "landtest",
  },
  {
    id: 33,
    title: "Seaside Spanish Villa",
    image: "Property14.png",
    size: 776,
    rent: 1480.88,
    bedrooms: 1,
    bathrooms: 8,
    neighbourhood: "Signal Hill",
    propertyType: "Apartment",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 34,
    title: "Luxe Lakeside Lodge",
    image: "Property15.png",
    size: 2167,
    rent: 1351.08,
    bedrooms: 1,
    bathrooms: 4,
    neighbourhood: "Windsor Park",
    propertyType: "House",
    landlord: "landtest",
  },
  {
    id: 35,
    title: "Modern Lakeside Retreat",
    image: "Property5.png",
    size: 2018,
    rent: 1250.51,
    bedrooms: 6,
    bathrooms: 2,
    neighbourhood: "Kensington",
    propertyType: "Room",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 36,
    title: "Serene Seaside Villa",
    image: "Property9.png",
    size: 1215,
    rent: 2193.33,
    bedrooms: 7,
    bathrooms: 6,
    neighbourhood: "Scarboro",
    propertyType: "Duplex",
    landlord: "landtest",
  },
  {
    id: 37,
    title: "Vintage Vineyard Cottage",
    image: "Property6.png",
    size: 411,
    rent: 955.75,
    bedrooms: 2,
    bathrooms: 7,
    neighbourhood: "Douglasdale/Glen",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 38,
    title: "Sleek Ski Chalet",
    image: "Property11.png",
    size: 703,
    rent: 1881.71,
    bedrooms: 1,
    bathrooms: 8,
    neighbourhood: "Sunnyside",
    propertyType: "Duplex",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 39,
    title: "Quaint Countryside Farmhouse",
    image: "Property4.png",
    size: 1614,
    rent: 2640.17,
    bedrooms: 5,
    bathrooms: 8,
    neighbourhood: "Westgate",
    propertyType: "Duplex",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 40,
    title: "Seaside Spanish Villa",
    image: "Property9.png",
    size: 2253,
    rent: 121.75,
    bedrooms: 3,
    bathrooms: 6,
    neighbourhood: "Roxboro",
    propertyType: "Basement",
    landlord: "resaLmother@email.com",
  },
  {
    id: 41,
    title: "Lakeside Log Cabin",
    image: "Property7.png",
    size: 1195,
    rent: 2988.46,
    bedrooms: 9,
    bathrooms: 8,
    neighbourhood: "Braeside",
    propertyType: "Room",
  },
  {
    id: 42,
    title: "Tropical Paradise Bungalow",
    image: "Property8.png",
    size: 1897,
    rent: 1806.33,
    bedrooms: 8,
    bathrooms: 2,
    neighbourhood: "Bowness",
    propertyType: "House",
    landlord: "landtest",
  },
  {
    id: 43,
    title: "Quaint Countryside Farmhouse",
    image: "Property1.png",
    size: 680,
    rent: 2345.92,
    bedrooms: 6,
    bathrooms: 2,
    neighbourhood: "Crestmont",
    propertyType: "Room",
    landlord: "landtest",
  },
  {
    id: 44,
    title: "Sleek Ski Chalet",
    image: "Property8.png",
    size: 616,
    rent: 750.84,
    bedrooms: 5,
    bathrooms: 9,
    neighbourhood: "Eau Claire",
    propertyType: "Duplex",
    landlord: "landtest",
  },
  {
    id: 45,
    title: "Historic Brownstone in the Heart of the City",
    image: "Property7.png",
    size: 1082,
    rent: 2022.87,
    bedrooms: 3,
    bathrooms: 3,
    neighbourhood: "Acadia",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 46,
    title: "Boutique Loft in the Arts District",
    image: "Property16.png",
    size: 1339,
    rent: 2672.91,
    bedrooms: 6,
    bathrooms: 4,
    neighbourhood: "Kingsland",
    propertyType: "Duplex",
    landlord: "landtest",
  },
  {
    id: 47,
    title: "Cozy Coastal Cottage",
    image: "Property15.png",
    size: 1283,
    rent: 765.82,
    bedrooms: 9,
    bathrooms: 4,
    neighbourhood: "Hillhurst",
    propertyType: "Apartment",
    landlord: "landtest",
  },
  {
    id: 48,
    title: "Bohemian Chic Townhouse",
    image: "Property6.png",
    size: 951,
    rent: 1656.17,
    bedrooms: 6,
    bathrooms: 9,
    neighbourhood: "Strathcona Park",
    propertyType: "Apartment",
    landlord: "resaLmother@email.com",
  },
  {
    id: 49,
    title: "Countryside Castle Cottage",
    image: "Property14.png",
    size: 228,
    rent: 551.03,
    bedrooms: 9,
    bathrooms: 4,
    neighbourhood: "Glenbrook",
    propertyType: "Basement",
  },
  {
    id: 50,
    title: "Minimalist Mountain Retreat",
    image: "Property18.png",
    size: 2137,
    rent: 1472.94,
    bedrooms: 6,
    bathrooms: 1,
    neighbourhood: "Mount Pleasant",
    propertyType: "House",
    landlord: "landtest",
  },
  {
    id: 51,
    title: "Serene Seaside Villa",
    image: "Property12.png",
    size: 1831,
    rent: 799.56,
    bedrooms: 1,
    bathrooms: 6,
    neighbourhood: "Douglasdale Estates",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 52,
    title: "Artsy Loft in the Arts District",
    image: "Property1.png",
    size: 801,
    rent: 292.56,
    bedrooms: 8,
    bathrooms: 8,
    neighbourhood: "Britannia",
    propertyType: "House",
    landlord: "landtest",
  },
  {
    id: 53,
    title: "Modern Lakeside Retreat",
    image: "Property4.png",
    size: 522,
    rent: 1921.92,
    bedrooms: 1,
    bathrooms: 9,
    neighbourhood: "Bridgeland",
    propertyType: "Basement",
    landlord: "resaLmother@email.com",
  },
  {
    id: 54,
    title: "Chic Countryside Manor",
    image: "Property17.png",
    size: 240,
    rent: 1353.71,
    bedrooms: 3,
    bathrooms: 2,
    neighbourhood: "Crescent Heights",
    propertyType: "House",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 55,
    title: "Scenic Mountain View Chalet",
    image: "Property17.png",
    size: 1933,
    rent: 1424.43,
    bedrooms: 5,
    bathrooms: 6,
    neighbourhood: "Acadia",
    propertyType: "Apartment",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 56,
    title: "Artsy Urban Studio",
    image: "Property8.png",
    size: 281,
    rent: 899.54,
    bedrooms: 5,
    bathrooms: 4,
    neighbourhood: "Southwood",
    propertyType: "Duplex",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 57,
    title: "Boho Beachfront Bungalow",
    image: "Property17.png",
    size: 1208,
    rent: 377.32,
    bedrooms: 5,
    bathrooms: 3,
    neighbourhood: "Strathcona Park",
    propertyType: "Room",
    landlord: "resaLmother@email.com",
  },
  {
    id: 58,
    title: "Tree-lined Suburban Sanctuary",
    image: "Property1.png",
    size: 1462,
    rent: 1085.81,
    bedrooms: 3,
    bathrooms: 8,
    neighbourhood: "Pump Hill",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 59,
    title: "Quaint Countryside Farmhouse",
    image: "Property13.png",
    size: 1489,
    rent: 1387.05,
    bedrooms: 2,
    bathrooms: 8,
    neighbourhood: "West Springs",
    propertyType: "House",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 60,
    title: "Quaint Countryside Farmhouse",
    image: "Property17.png",
    size: 1907,
    rent: 2290.3,
    bedrooms: 7,
    bathrooms: 6,
    neighbourhood: "Capitol Hill",
    propertyType: "Duplex",
  },
  {
    id: 61,
    title: "Historic Brownstone in the Heart of the City",
    image: "Property15.png",
    size: 1770,
    rent: 2879.49,
    bedrooms: 1,
    bathrooms: 8,
    neighbourhood: "Strathcona Park",
    propertyType: "Apartment",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 62,
    title: "Tranquil Retreat Cottage",
    image: "Property1.png",
    size: 1292,
    rent: 1777.42,
    bedrooms: 8,
    bathrooms: 2,
    neighbourhood: "Discovery Ridge",
    propertyType: "Basement",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 63,
    title: "Historic Brownstone in the Heart of the City",
    image: "Property18.png",
    size: 546,
    rent: 2667.55,
    bedrooms: 4,
    bathrooms: 1,
    neighbourhood: "Patterson",
    propertyType: "Basement",
    landlord: "resaLmother@email.com",
  },
  {
    id: 64,
    title: "Treehouse Haven Hideaway",
    image: "Property18.png",
    size: 1459,
    rent: 1794.51,
    bedrooms: 6,
    bathrooms: 3,
    neighbourhood: "Braeside",
    propertyType: "Room",
    landlord: "landtest",
  },
  {
    id: 65,
    title: "Historic Brownstone in the Heart of the City",
    image: "Property13.png",
    size: 356,
    rent: 2555.74,
    bedrooms: 4,
    bathrooms: 3,
    neighbourhood: "Cedarbrae",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 66,
    title: "Enchanting Garden Cottage",
    image: "Property5.png",
    size: 1637,
    rent: 2516.52,
    bedrooms: 2,
    bathrooms: 1,
    neighbourhood: "Inglewood",
    propertyType: "Duplex",
  },
  {
    id: 67,
    title: "Artsy Urban Studio",
    image: "Property10.png",
    size: 1634,
    rent: 1167.11,
    bedrooms: 6,
    bathrooms: 8,
    neighbourhood: "Glengarry",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 68,
    title: "Sunset Beach Bungalow",
    image: "Property12.png",
    size: 411,
    rent: 199.33,
    bedrooms: 2,
    bathrooms: 4,
    neighbourhood: "Palliser",
    propertyType: "Apartment",
    landlord: "landtest",
  },
  {
    id: 69,
    title: "Chic City View Apartment",
    image: "Property8.png",
    size: 2005,
    rent: 1458.94,
    bedrooms: 9,
    bathrooms: 6,
    neighbourhood: "St. Andrews Heights",
    propertyType: "Basement",
  },
  {
    id: 70,
    title: "Rustic Riverside Retreat",
    image: "Property12.png",
    size: 1607,
    rent: 1612.61,
    bedrooms: 2,
    bathrooms: 7,
    neighbourhood: "Willow Park",
    propertyType: "Apartment",
  },
  {
    id: 71,
    title: "Tropical Paradise Bungalow",
    image: "Property10.png",
    size: 312,
    rent: 2310.31,
    bedrooms: 3,
    bathrooms: 2,
    neighbourhood: "Mission",
    propertyType: "House",
    landlord: "resaLmother@email.com",
  },
  {
    id: 72,
    title: "Serene Seaside Villa",
    image: "Property7.png",
    size: 1466,
    rent: 1549.4,
    bedrooms: 5,
    bathrooms: 7,
    neighbourhood: "Mission",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 73,
    title: "Chic City View Apartment",
    image: "Property18.png",
    size: 1274,
    rent: 157.85,
    bedrooms: 9,
    bathrooms: 6,
    neighbourhood: "Montgomery",
    propertyType: "Duplex",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 74,
    title: "Sunset Beach Bungalow",
    image: "Property7.png",
    size: 2005,
    rent: 1258.49,
    bedrooms: 8,
    bathrooms: 6,
    neighbourhood: "Killarney/Glengarry",
    propertyType: "Room",
    landlord: "landtest",
  },
  {
    id: 75,
    title: "Sleek Ski Chalet",
    image: "Property11.png",
    size: 382,
    rent: 909.75,
    bedrooms: 2,
    bathrooms: 5,
    neighbourhood: "Beltline",
    propertyType: "Basement",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 76,
    title: "Boho Beachfront Bungalow",
    image: "Property3.png",
    size: 2386,
    rent: 2465.68,
    bedrooms: 7,
    bathrooms: 7,
    neighbourhood: "Bankview",
    propertyType: "Apartment",
    landlord: "landtest",
  },
  {
    id: 77,
    title: "Quirky Quarters in the City",
    image: "Property7.png",
    size: 1169,
    rent: 1934.6,
    bedrooms: 6,
    bathrooms: 2,
    neighbourhood: "Maple Ridge",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 78,
    title: "Historic Brownstone in the Heart of the City",
    image: "Property7.png",
    size: 1967,
    rent: 1076.0,
    bedrooms: 7,
    bathrooms: 1,
    neighbourhood: "Highland Park",
    propertyType: "Duplex",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 79,
    title: "Cozy Coastal Cottage",
    image: "Property14.png",
    size: 1283,
    rent: 666.77,
    bedrooms: 8,
    bathrooms: 8,
    neighbourhood: "Glengarry",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 80,
    title: "City Lights View Penthouse",
    image: "Property3.png",
    size: 1009,
    rent: 1984.36,
    bedrooms: 1,
    bathrooms: 6,
    neighbourhood: "Kingsland",
    propertyType: "Apartment",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 81,
    title: "Artsy Loft in the Arts District",
    image: "Property14.png",
    size: 265,
    rent: 1625.3,
    bedrooms: 2,
    bathrooms: 6,
    neighbourhood: "Tuxedo Park",
    propertyType: "Duplex",
  },
  {
    id: 82,
    title: "Boutique Loft in the Arts District",
    image: "Property6.png",
    size: 1705,
    rent: 1176.4,
    bedrooms: 9,
    bathrooms: 6,
    neighbourhood: "Rosedale",
    propertyType: "Room",
  },
  {
    id: 83,
    title: "Elegant Downtown Penthouse",
    image: "Property3.png",
    size: 2369,
    rent: 2682.17,
    bedrooms: 2,
    bathrooms: 4,
    neighbourhood: "Aspen Woods",
    propertyType: "Room",
    landlord: "resaLmother@email.com",
  },
  {
    id: 84,
    title: "Chic Countryside Manor",
    image: "Property18.png",
    size: 2126,
    rent: 2179.08,
    bedrooms: 8,
    bathrooms: 7,
    neighbourhood: "Renfrew",
    propertyType: "Apartment",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 85,
    title: "City Lights View Penthouse",
    image: "Property12.png",
    size: 2068,
    rent: 755.44,
    bedrooms: 3,
    bathrooms: 6,
    neighbourhood: "Braeside",
    propertyType: "Room",
  },
  {
    id: 86,
    title: "Charming Farmstay Cottage",
    image: "Property5.png",
    size: 2363,
    rent: 2911.08,
    bedrooms: 7,
    bathrooms: 6,
    neighbourhood: "Glenbrook",
    propertyType: "Duplex",
    landlord: "resaLmother@email.com",
  },
  {
    id: 87,
    title: "Enchanting Garden Cottage",
    image: "Property5.png",
    size: 641,
    rent: 2101.97,
    bedrooms: 1,
    bathrooms: 9,
    neighbourhood: "Douglasdale Estates",
    propertyType: "Basement",
    landlord: "resaLmother@email.com",
  },
  {
    id: 88,
    title: "City Lights View Penthouse",
    image: "Property5.png",
    size: 2353,
    rent: 794.67,
    bedrooms: 9,
    bathrooms: 3,
    neighbourhood: "Braeside",
    propertyType: "House",
    landlord: "resaLmother@email.com",
  },
  {
    id: 89,
    title: "Mountain Haven Chalet",
    image: "Property15.png",
    size: 2323,
    rent: 362.49,
    bedrooms: 7,
    bathrooms: 2,
    neighbourhood: "Deer Ridge",
    propertyType: "Apartment",
    landlord: "resaLmother@email.com",
  },
  {
    id: 90,
    title: "Seaside Spanish Villa",
    image: "Property3.png",
    size: 499,
    rent: 2383.87,
    bedrooms: 6,
    bathrooms: 8,
    neighbourhood: "Southwood",
    propertyType: "Room",
    landlord: "landtest",
  },
  {
    id: 91,
    title: "Quaint Countryside Farmhouse",
    image: "Property9.png",
    size: 1595,
    rent: 2181.71,
    bedrooms: 2,
    bathrooms: 4,
    neighbourhood: "Bowness",
    propertyType: "Basement",
    landlord: "landtest",
  },
  {
    id: 92,
    title: "Rustic Riverside Retreat",
    image: "Property13.png",
    size: 528,
    rent: 617.74,
    bedrooms: 2,
    bathrooms: 2,
    neighbourhood: "Downtown East Village",
    propertyType: "Duplex",
  },
  {
    id: 93,
    title: "Luxe Lakeside Lodge",
    image: "Property7.png",
    size: 915,
    rent: 1903.94,
    bedrooms: 8,
    bathrooms: 3,
    neighbourhood: "Rutland Park",
    propertyType: "Basement",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 94,
    title: "Cozy Coastal Cottage",
    image: "Property2.png",
    size: 2131,
    rent: 1832.78,
    bedrooms: 8,
    bathrooms: 8,
    neighbourhood: "Southwood",
    propertyType: "House",
    landlord: "resaLmother@email.com",
  },
  {
    id: 95,
    title: "Mountain Haven Chalet",
    image: "Property2.png",
    size: 648,
    rent: 970.54,
    bedrooms: 5,
    bathrooms: 1,
    neighbourhood: "Killarney",
    propertyType: "Apartment",
    landlord: "landtest",
  },
  {
    id: 96,
    title: "Boho Beachfront Bungalow",
    image: "Property8.png",
    size: 342,
    rent: 831.65,
    bedrooms: 8,
    bathrooms: 3,
    neighbourhood: "Queensland",
    propertyType: "Apartment",
    landlord: "resaLmother@email.com",
  },
  {
    id: 97,
    title: "Countryside Castle Cottage",
    image: "Property3.png",
    size: 1527,
    rent: 2706.29,
    bedrooms: 7,
    bathrooms: 8,
    neighbourhood: "Douglasdale/Glen",
    propertyType: "House",
    landlord: "resaLmother@email.com",
  },
  {
    id: 98,
    title: "Sleek Ski Chalet",
    image: "Property1.png",
    size: 1092,
    rent: 1442.67,
    bedrooms: 6,
    bathrooms: 4,
    neighbourhood: "Rutland Park",
    propertyType: "Apartment",
  },
  {
    id: 99,
    title: "Modern Lakeside Retreat",
    image: "Property3.png",
    size: 831,
    rent: 497.58,
    bedrooms: 4,
    bathrooms: 4,
    neighbourhood: "Douglasdale/Glen",
    propertyType: "Duplex",
  },
  {
    id: 100,
    title: "Mid-Century Modern Gem",
    image: "Property6.png",
    size: 763,
    rent: 1664.23,
    bedrooms: 1,
    bathrooms: 2,
    neighbourhood: "Scarboro",
    propertyType: "Room",
  },
];
export const getProperties = () => propertyList;
export const removeProperty = (id, u) => {
  propertyList = propertyList.filter(
    (prop) => !(prop.id === id && prop.landlord === u)
  );
};
export const addProperty =(data)=>{
  propertyList.push(data);
}
export const editProperty = (index,data)=>{
  propertyList[index] = data;
}
export default propertyList;
