const propertyList = [
  {
    title: "House on a Hill",
    image: "Property1.png",
    size: 1200,
    rent: 899.99,
    bedrooms: 2,
    bathrooms: 1,
    neighbourhood: "Evanston",
  },
  {
    title: "Modern Downtown Loft",
    image: "Property2.png",
    size: 1800,
    rent: 1099.99,
    bedrooms: 2,
    bathrooms: 2,
    neighbourhood: "Downtown",
    landlord: "testLandlord@email.com",
  },
  {
    title: "Spacious Family Home",
    image: "Property3.png",
    size: 2500,
    rent: 1399.99,
    bedrooms: 4,
    bathrooms: 3,
    neighbourhood: "Arbour Lake",
  },
  {
    title: "Unique Hidden Home",
    image: "Property4.png",
    size: 2000,
    rent: 899.99,
    bedrooms: 4,
    bathrooms: 3,
    neighbourhood: "Downtown",
    landlord: "testLandlord@email.com",
  },
  {
    title: "Cozy Apartment",
    image: "Property5.png",
    size: 1200,
    rent: 899.99,
    bedrooms: 2,
    bathrooms: 2,
    neighbourhood: "Downtown",
  },
  {
    title: "Suburban Home",
    image: "Property6.png",
    size: 1800,
    rent: 1299.99,
    bedrooms: 4,
    bathrooms: 3,
    neighbourhood: "Downtown",
  },
  {
    title: "Modern Urban Oasis",
    image: "Property7.png",
    size: 1600,
    rent: 999.99,
    bedrooms: 3,
    bathrooms: 2,
    neighbourhood: "Crescent Heights",
  },
  {
    title: "Family-Friendly Home",
    image: "Property8.png",
    size: 2200,
    rent: 1399.99,
    bedrooms: 4,
    bathrooms: 3,
    neighbourhood: "Downtown",
    landlord: "testLandlord@email.com",
  },
  {
    title: "Stylish Modern Apartment",
    image: "Property9.png",
    size: 1400,
    rent: 799.99,
    bedrooms: 2,
    bathrooms: 2,
    neighbourhood: "Downtown",
  },
  {
    id: 1,
    title: "Serene Cityscape Haven",
    image: "Property7.png",
    size: 1420,
    rent: 3803.2,
    bedrooms: 6,
    bathrooms: 11,
    neighbourhood: "Eagle Ridge",
    landlord: "testLandlord@email.com",
  },
  {
    id: 2,
    title: "Rustic Riverside Cabin",
    image: "Property8.png",
    size: 1049,
    rent: 447.8,
    bedrooms: 3,
    bathrooms: 16,
    neighbourhood: "Coventry Hills",
    landlord: "testLandlord@email.com",
  },
  {
    id: 3,
    title: "Quaint Countryside Cottage",
    image: "Property5.png",
    size: 1082,
    rent: 243.0,
    bedrooms: 3,
    bathrooms: 4,
    neighbourhood: "Highland Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 4,
    title: "Lakeside Lodge Sanctuary",
    image: "Property8.png",
    size: 2142,
    rent: 2045.6,
    bedrooms: 1,
    bathrooms: 13,
    neighbourhood: "Cambrian Heights",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 5,
    title: "Seaside Serenity Villa",
    image: "Property1.png",
    size: 2129,
    rent: 932.8,
    bedrooms: 4,
    bathrooms: 1,
    neighbourhood: "Beddington",
    landlord: "testLandlord@email.com",
  },
  {
    id: 6,
    title: "Sunset Splendor Villa",
    image: "Property5.png",
    size: 405,
    rent: 1171.1,
    bedrooms: 13,
    bathrooms: 6,
    neighbourhood: "Chinatown",
    landlord: "testLandlord@email.com",
  },
  {
    id: 7,
    title: "Skyline Splendor Penthouse",
    image: "Property4.png",
    size: 2795,
    rent: 1582.5,
    bedrooms: 11,
    bathrooms: 6,
    neighbourhood: "Chinatown",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 8,
    title: "Harborview Harbor House",
    image: "Property9.png",
    size: 865,
    rent: 2074.3,
    bedrooms: 7,
    bathrooms: 7,
    neighbourhood: "Acadia",
    landlord: "testLandlord@email.com",
  },
  {
    id: 9,
    title: "Retro Revival Residence",
    image: "Property3.png",
    size: 455,
    rent: 1977.9,
    bedrooms: 14,
    bathrooms: 5,
    neighbourhood: "Capitol Hill",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 10,
    title: "Seaside Splendor Cottage",
    image: "Property9.png",
    size: 2700,
    rent: 3843.5,
    bedrooms: 0,
    bathrooms: 10,
    neighbourhood: "Brentwood",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 11,
    title: "Homestead Haven Hideout",
    image: "Property9.png",
    size: 2466,
    rent: 2113.5,
    bedrooms: 10,
    bathrooms: 20,
    neighbourhood: "Sunnyside",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 12,
    title: "Vintage Charm Cottage",
    image: "Property3.png",
    size: 2592,
    rent: 2105.4,
    bedrooms: 4,
    bathrooms: 11,
    neighbourhood: "Haysboro",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 13,
    title: "Serene Cityscape Haven",
    image: "Property6.png",
    size: 955,
    rent: 2264.2,
    bedrooms: 3,
    bathrooms: 5,
    neighbourhood: "Cedarbrae",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 14,
    title: "Uptown Urban Retreat",
    image: "Property2.png",
    size: 2730,
    rent: 3509.9,
    bedrooms: 2,
    bathrooms: 0,
    neighbourhood: "Glenbrook",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 15,
    title: "Boho Beachfront Bungalow",
    image: "Property1.png",
    size: 1662,
    rent: 1312.1,
    bedrooms: 6,
    bathrooms: 1,
    neighbourhood: "Capitol Hill",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 16,
    title: "Seaside Serenity Villa",
    image: "Property8.png",
    size: 1880,
    rent: 3573.8,
    bedrooms: 11,
    bathrooms: 11,
    neighbourhood: "Acadia",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 17,
    title: "Panoramic Peak View Chalet",
    image: "Property5.png",
    size: 2896,
    rent: 1621.9,
    bedrooms: 10,
    bathrooms: 9,
    neighbourhood: "Greenview",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 18,
    title: "Nature's Nest Hideaway",
    image: "Property7.png",
    size: 2349,
    rent: 1848.9,
    bedrooms: 4,
    bathrooms: 7,
    neighbourhood: "Brentwood",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 19,
    title: "Boho Beachfront Bungalow",
    image: "Property6.png",
    size: 2725,
    rent: 498.7,
    bedrooms: 0,
    bathrooms: 14,
    neighbourhood: "Christie Park",
    landlord: "testLandlord@email.com",
  },
  {
    id: 20,
    title: "Vintage Charm Cottage",
    image: "Property6.png",
    size: 1672,
    rent: 1365.4,
    bedrooms: 9,
    bathrooms: 14,
    neighbourhood: "Glamorgan",
    landlord: "testLandlord@email.com",
  },
  {
    id: 21,
    title: "Rustic Elegance Cabin",
    image: "Property4.png",
    size: 2049,
    rent: 665.2,
    bedrooms: 9,
    bathrooms: 13,
    neighbourhood: "Highland Park",
    landlord: "testLandlord@email.com",
  },
  {
    id: 22,
    title: "Lakeshore Luxury Villa",
    image: "Property7.png",
    size: 1460,
    rent: 1983.6,
    bedrooms: 12,
    bathrooms: 3,
    neighbourhood: "Collingwood",
    landlord: "testLandlord@email.com",
  },
  {
    id: 23,
    title: "Seaside Splendor Cottage",
    image: "Property4.png",
    size: 927,
    rent: 1282.4,
    bedrooms: 7,
    bathrooms: 12,
    neighbourhood: "Inglewood",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 24,
    title: "Waterfront Whimsy Cottage",
    image: "Property7.png",
    size: 400,
    rent: 2415.3,
    bedrooms: 12,
    bathrooms: 10,
    neighbourhood: "Beddington",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 25,
    title: "Enchanting Garden Getaway",
    image: "Property3.png",
    size: 515,
    rent: 1380.9,
    bedrooms: 0,
    bathrooms: 5,
    neighbourhood: "Discovery Ridge",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 26,
    title: "Mountain Majesty Mansion",
    image: "Property8.png",
    size: 2912,
    rent: 3330.9,
    bedrooms: 12,
    bathrooms: 8,
    neighbourhood: "Elbow Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 27,
    title: "Mountain Majesty Mansion",
    image: "Property4.png",
    size: 2081,
    rent: 3776.8,
    bedrooms: 0,
    bathrooms: 0,
    neighbourhood: "Varsity",
    landlord: "testLandlord@email.com",
  },
  {
    id: 28,
    title: "Uptown Urban Retreat",
    image: "Property2.png",
    size: 2086,
    rent: 3186.4,
    bedrooms: 10,
    bathrooms: 1,
    neighbourhood: "Glenbrook",
    landlord: "testLandlord@email.com",
  },
  {
    id: 29,
    title: "Riverside Romance Retreat",
    image: "Property5.png",
    size: 2921,
    rent: 261.1,
    bedrooms: 4,
    bathrooms: 13,
    neighbourhood: "Chinatown",
    landlord: "testLandlord@email.com",
  },
  {
    id: 30,
    title: "Lakeside Lullaby Lodge",
    image: "Property5.png",
    size: 2908,
    rent: 2950.1,
    bedrooms: 2,
    bathrooms: 2,
    neighbourhood: "Eagle Ridge",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 31,
    title: "Harborview Harbor House",
    image: "Property4.png",
    size: 1775,
    rent: 839.1,
    bedrooms: 10,
    bathrooms: 11,
    neighbourhood: "Rosedale",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 32,
    title: "Secluded Sanctuary Cottage",
    image: "Property7.png",
    size: 1613,
    rent: 1677.2,
    bedrooms: 5,
    bathrooms: 8,
    neighbourhood: "Evergreen",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 33,
    title: "Vintage Charm Cottage",
    image: "Property9.png",
    size: 2255,
    rent: 361.1,
    bedrooms: 1,
    bathrooms: 19,
    neighbourhood: "Forest Lawn",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 34,
    title: "Quaint Countryside Cottage",
    image: "Property9.png",
    size: 2158,
    rent: 3116.8,
    bedrooms: 5,
    bathrooms: 1,
    neighbourhood: "Copperfield",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 35,
    title: "Cozy Cabin Retreat",
    image: "Property5.png",
    size: 1847,
    rent: 876.4,
    bedrooms: 1,
    bathrooms: 7,
    neighbourhood: "Chinatown",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 36,
    title: "Skyline Splendor Penthouse",
    image: "Property3.png",
    size: 1440,
    rent: 409.7,
    bedrooms: 14,
    bathrooms: 10,
    neighbourhood: "Greenview",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 37,
    title: "Cozy Cabin Retreat",
    image: "Property1.png",
    size: 1098,
    rent: 259.0,
    bedrooms: 6,
    bathrooms: 6,
    neighbourhood: "Inglewood",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 38,
    title: "Treehouse Retreat",
    image: "Property4.png",
    size: 1646,
    rent: 369.2,
    bedrooms: 0,
    bathrooms: 15,
    neighbourhood: "Tuxedo Park",
    landlord: "testLandlord@email.com",
  },
  {
    id: 39,
    title: "Lakeshore Luxury Villa",
    image: "Property5.png",
    size: 1964,
    rent: 3552.8,
    bedrooms: 3,
    bathrooms: 4,
    neighbourhood: "Haysboro",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 40,
    title: "Dreamy Desert Oasis",
    image: "Property7.png",
    size: 1746,
    rent: 1568.5,
    bedrooms: 6,
    bathrooms: 1,
    neighbourhood: "Coventry Hills",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 41,
    title: "City Lights Penthouse",
    image: "Property9.png",
    size: 2291,
    rent: 1233.0,
    bedrooms: 2,
    bathrooms: 6,
    neighbourhood: "Arbour Lake",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 42,
    title: "Harborview Harbor House",
    image: "Property9.png",
    size: 2417,
    rent: 1896.8,
    bedrooms: 11,
    bathrooms: 14,
    neighbourhood: "Dalhousie",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 43,
    title: "Modern Luxury Loft",
    image: "Property5.png",
    size: 2535,
    rent: 377.2,
    bedrooms: 7,
    bathrooms: 3,
    neighbourhood: "Acadia",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 44,
    title: "Boho Beachfront Bungalow",
    image: "Property1.png",
    size: 2317,
    rent: 1185.7,
    bedrooms: 13,
    bathrooms: 15,
    neighbourhood: "Eagle Ridge",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 45,
    title: "Quaint Countryside Cottage",
    image: "Property6.png",
    size: 443,
    rent: 247.6,
    bedrooms: 6,
    bathrooms: 14,
    neighbourhood: "Beddington",
    landlord: "testLandlord@email.com",
  },
  {
    id: 46,
    title: "Cozy Cabin Retreat",
    image: "Property7.png",
    size: 2777,
    rent: 291.7,
    bedrooms: 5,
    bathrooms: 12,
    neighbourhood: "Dalhousie",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 47,
    title: "Harborview Harbor House",
    image: "Property2.png",
    size: 1417,
    rent: 2425.4,
    bedrooms: 1,
    bathrooms: 2,
    neighbourhood: "Greenview",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 48,
    title: "Zen Garden Oasis",
    image: "Property2.png",
    size: 1555,
    rent: 3097.3,
    bedrooms: 2,
    bathrooms: 5,
    neighbourhood: "Collingwood",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 49,
    title: "Elegant Escape Estate",
    image: "Property9.png",
    size: 634,
    rent: 1053.2,
    bedrooms: 10,
    bathrooms: 1,
    neighbourhood: "Tuxedo Park",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 50,
    title: "Sunset Bliss Bungalow",
    image: "Property9.png",
    size: 2740,
    rent: 752.3,
    bedrooms: 2,
    bathrooms: 13,
    neighbourhood: "Canyon Meadows",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 51,
    title: "Seaside Splendor Cottage",
    image: "Property6.png",
    size: 1137,
    rent: 1844.9,
    bedrooms: 9,
    bathrooms: 0,
    neighbourhood: "Ramsay",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 52,
    title: "Coastal Paradise Cove",
    image: "Property4.png",
    size: 2266,
    rent: 2163.3,
    bedrooms: 11,
    bathrooms: 14,
    neighbourhood: "Cliff Bungalow",
    landlord: "testLandlord@email.com",
  },
  {
    id: 53,
    title: "Coastal Paradise Cove",
    image: "Property4.png",
    size: 1238,
    rent: 1464.6,
    bedrooms: 6,
    bathrooms: 17,
    neighbourhood: "Sunnyside",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 54,
    title: "Artisan Loft Hideout",
    image: "Property5.png",
    size: 2711,
    rent: 2358.1,
    bedrooms: 10,
    bathrooms: 1,
    neighbourhood: "Glamorgan",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 55,
    title: "Lakeside Lullaby Lodge",
    image: "Property5.png",
    size: 1273,
    rent: 1325.7,
    bedrooms: 7,
    bathrooms: 10,
    neighbourhood: "Varsity",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 56,
    title: "Boho Beachfront Bungalow",
    image: "Property3.png",
    size: 2114,
    rent: 2870.1,
    bedrooms: 9,
    bathrooms: 14,
    neighbourhood: "Beddington",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 57,
    title: "Lakeside Lodge Sanctuary",
    image: "Property2.png",
    size: 1949,
    rent: 2382.5,
    bedrooms: 0,
    bathrooms: 16,
    neighbourhood: "Erlton",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 58,
    title: "Rustic Riverside Cabin",
    image: "Property9.png",
    size: 924,
    rent: 2565.8,
    bedrooms: 13,
    bathrooms: 15,
    neighbourhood: "Bridgeland",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 59,
    title: "Quaint Countryside Cottage",
    image: "Property1.png",
    size: 525,
    rent: 906.3,
    bedrooms: 15,
    bathrooms: 16,
    neighbourhood: "Cedarbrae",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 60,
    title: "Retro Revival Residence",
    image: "Property9.png",
    size: 2853,
    rent: 604.6,
    bedrooms: 6,
    bathrooms: 4,
    neighbourhood: "Bridgeland",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 61,
    title: "Blissful Beach House",
    image: "Property3.png",
    size: 820,
    rent: 1413.7,
    bedrooms: 5,
    bathrooms: 20,
    neighbourhood: "Killarney.",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 62,
    title: "Mountain Majesty Manor",
    image: "Property1.png",
    size: 1308,
    rent: 3485.1,
    bedrooms: 13,
    bathrooms: 5,
    neighbourhood: "Elbow Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 63,
    title: "Nature's Nest Hideaway",
    image: "Property8.png",
    size: 2643,
    rent: 2225.8,
    bedrooms: 9,
    bathrooms: 14,
    neighbourhood: "Bridgeland",
    landlord: "testLandlord@email.com",
  },
  {
    id: 64,
    title: "Mountain Majesty Mansion",
    image: "Property5.png",
    size: 1508,
    rent: 2898.6,
    bedrooms: 9,
    bathrooms: 18,
    neighbourhood: "Mission",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 65,
    title: "Skyline Splendor Penthouse",
    image: "Property5.png",
    size: 1915,
    rent: 821.3,
    bedrooms: 14,
    bathrooms: 15,
    neighbourhood: "Bridgeland",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 66,
    title: "Rustic Elegance Cabin",
    image: "Property5.png",
    size: 2496,
    rent: 3095.5,
    bedrooms: 0,
    bathrooms: 10,
    neighbourhood: "Elbow Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 67,
    title: "Contemporary Comfort Condo",
    image: "Property4.png",
    size: 2374,
    rent: 682.9,
    bedrooms: 2,
    bathrooms: 3,
    neighbourhood: "Dalhousie",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 68,
    title: "Blissful Beach House",
    image: "Property1.png",
    size: 1437,
    rent: 1542.4,
    bedrooms: 8,
    bathrooms: 19,
    neighbourhood: "Erlton",
    landlord: "testLandlord@email.com",
  },
  {
    id: 69,
    title: "Mountain View Hideaway",
    image: "Property4.png",
    size: 1331,
    rent: 2940.2,
    bedrooms: 6,
    bathrooms: 14,
    neighbourhood: "Kensington",
    landlord: "testLandlord@email.com",
  },
  {
    id: 70,
    title: "Whimsical Woodland Cabin",
    image: "Property2.png",
    size: 1722,
    rent: 1396.6,
    bedrooms: 5,
    bathrooms: 10,
    neighbourhood: "Christie Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 71,
    title: "Seaside Splendor Cottage",
    image: "Property6.png",
    size: 1746,
    rent: 242.5,
    bedrooms: 7,
    bathrooms: 19,
    neighbourhood: "Coach Hill",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 72,
    title: "Secret Garden Villa",
    image: "Property5.png",
    size: 1317,
    rent: 381.5,
    bedrooms: 9,
    bathrooms: 4,
    neighbourhood: "Montgomery",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 73,
    title: "Riverside Romance Retreat",
    image: "Property5.png",
    size: 2290,
    rent: 2917.9,
    bedrooms: 3,
    bathrooms: 18,
    neighbourhood: "Killarney.",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 74,
    title: "Secluded Sanctuary Cottage",
    image: "Property5.png",
    size: 417,
    rent: 1871.8,
    bedrooms: 11,
    bathrooms: 12,
    neighbourhood: "Beltline",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 75,
    title: "Harborview Harbor House",
    image: "Property7.png",
    size: 2564,
    rent: 1699.7,
    bedrooms: 13,
    bathrooms: 16,
    neighbourhood: "Christie Park",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 76,
    title: "Coastal Paradise Cove",
    image: "Property5.png",
    size: 1067,
    rent: 1016.0,
    bedrooms: 14,
    bathrooms: 9,
    neighbourhood: "Evergreen",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 77,
    title: "Treehouse Retreat",
    image: "Property8.png",
    size: 1217,
    rent: 3654.8,
    bedrooms: 0,
    bathrooms: 6,
    neighbourhood: "Eagle Ridge",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 78,
    title: "Tranquil Treetop Cabin",
    image: "Property7.png",
    size: 2555,
    rent: 464.9,
    bedrooms: 10,
    bathrooms: 1,
    neighbourhood: "Erlton",
    landlord: "testLandlord@email.com",
  },
  {
    id: 79,
    title: "Urban Oasis Retreat",
    image: "Property3.png",
    size: 1271,
    rent: 3193.4,
    bedrooms: 3,
    bathrooms: 3,
    neighbourhood: "Arbour Lake",
    landlord: "testLandlord@email.com",
  },
  {
    id: 80,
    title: "Seaside Serenity Villa",
    image: "Property3.png",
    size: 638,
    rent: 2585.7,
    bedrooms: 1,
    bathrooms: 8,
    neighbourhood: "Dover",
    landlord: "testLandlord@email.com",
  },
  {
    id: 81,
    title: "Lakeside Lullaby Lodge",
    image: "Property8.png",
    size: 1188,
    rent: 3795.8,
    bedrooms: 10,
    bathrooms: 16,
    neighbourhood: "Mission",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 82,
    title: "Nature's Nest Hideaway",
    image: "Property7.png",
    size: 2308,
    rent: 2889.7,
    bedrooms: 2,
    bathrooms: 12,
    neighbourhood: "Rosedale",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 83,
    title: "Sunset Bliss Bungalow",
    image: "Property7.png",
    size: 497,
    rent: 2641.8,
    bedrooms: 2,
    bathrooms: 1,
    neighbourhood: "Kelvin Grove",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 84,
    title: "Rustic Riverside Cabin",
    image: "Property7.png",
    size: 651,
    rent: 3722.4,
    bedrooms: 4,
    bathrooms: 2,
    neighbourhood: "Killarney.",
    landlord: "testLandlord@email.com",
  },
  {
    id: 85,
    title: "Lakeside Luxury Lodge",
    image: "Property6.png",
    size: 1120,
    rent: 3952.7,
    bedrooms: 8,
    bathrooms: 13,
    neighbourhood: "Killarney.",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 86,
    title: "Tranquil Treetop Cabin",
    image: "Property7.png",
    size: 1922,
    rent: 3195.3,
    bedrooms: 13,
    bathrooms: 10,
    neighbourhood: "Highland Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 87,
    title: "Zen Garden Oasis",
    image: "Property6.png",
    size: 976,
    rent: 3298.4,
    bedrooms: 11,
    bathrooms: 1,
    neighbourhood: "Varsity",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 88,
    title: "Panoramic Peak View Chalet",
    image: "Property3.png",
    size: 799,
    rent: 672.9,
    bedrooms: 2,
    bathrooms: 13,
    neighbourhood: "Haysboro",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 89,
    title: "Treehouse Retreat",
    image: "Property5.png",
    size: 2508,
    rent: 3234.1,
    bedrooms: 1,
    bathrooms: 6,
    neighbourhood: "Highland Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 90,
    title: "Treehouse Retreat",
    image: "Property8.png",
    size: 803,
    rent: 3094.2,
    bedrooms: 8,
    bathrooms: 4,
    neighbourhood: "Kelvin Grove",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 91,
    title: "Cozy Cabin Retreat",
    image: "Property5.png",
    size: 2573,
    rent: 3405.2,
    bedrooms: 2,
    bathrooms: 14,
    neighbourhood: "Copperfield",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 92,
    title: "Modern Luxury Loft",
    image: "Property5.png",
    size: 2220,
    rent: 911.8,
    bedrooms: 1,
    bathrooms: 16,
    neighbourhood: "Beltline",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 93,
    title: "Lakeside Tranquility Cottage",
    image: "Property2.png",
    size: 2595,
    rent: 792.4,
    bedrooms: 7,
    bathrooms: 10,
    neighbourhood: "Erlton",
    landlord: "testLandlord@email.com",
  },
  {
    id: 94,
    title: "Skyline Splendor Penthouse",
    image: "Property6.png",
    size: 1119,
    rent: 1459.5,
    bedrooms: 8,
    bathrooms: 10,
    neighbourhood: "Christie Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 95,
    title: "Moonlit Magic Manor",
    image: "Property3.png",
    size: 1250,
    rent: 1576.3,
    bedrooms: 15,
    bathrooms: 4,
    neighbourhood: "Greenview",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 96,
    title: "Mountain Majesty Manor",
    image: "Property3.png",
    size: 1478,
    rent: 3756.8,
    bedrooms: 9,
    bathrooms: 18,
    neighbourhood: "Bankview",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 97,
    title: "Charming Cottage Escape",
    image: "Property6.png",
    size: 2010,
    rent: 1970.0,
    bedrooms: 9,
    bathrooms: 7,
    neighbourhood: "Acadia",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 98,
    title: "Secret Garden Villa",
    image: "Property2.png",
    size: 1310,
    rent: 2450.8,
    bedrooms: 6,
    bathrooms: 11,
    neighbourhood: "Kensington",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 99,
    title: "Sunset Bliss Bungalow",
    image: "Property2.png",
    size: 1564,
    rent: 3365.9,
    bedrooms: 5,
    bathrooms: 5,
    neighbourhood: "Christie Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 100,
    title: "Boho Beachfront Bungalow",
    image: "Property6.png",
    size: 1178,
    rent: 1609.3,
    bedrooms: 10,
    bathrooms: 7,
    neighbourhood: "Kelvin Grove",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 101,
    title: "Elegant Escape Estate",
    image: "Property1.png",
    size: 645,
    rent: 2596.0,
    bedrooms: 15,
    bathrooms: 5,
    neighbourhood: "Mount Royal",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 102,
    title: "Bohemian Chic Haven",
    image: "Property9.png",
    size: 1907,
    rent: 2513.2,
    bedrooms: 7,
    bathrooms: 11,
    neighbourhood: "Glendale",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 103,
    title: "Panoramic Peak View Chalet",
    image: "Property9.png",
    size: 2781,
    rent: 1972.8,
    bedrooms: 3,
    bathrooms: 5,
    neighbourhood: "Kelvin Grove",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 104,
    title: "Treehouse Retreat",
    image: "Property8.png",
    size: 2320,
    rent: 3560.0,
    bedrooms: 5,
    bathrooms: 9,
    neighbourhood: "Mission",
    landlord: "testLandlord@email.com",
  },
  {
    id: 105,
    title: "Boho Bliss Bungalow",
    image: "Property5.png",
    size: 2698,
    rent: 1306.5,
    bedrooms: 12,
    bathrooms: 18,
    neighbourhood: "Capitol Hill",
    landlord: "testLandlord@email.com",
  },
  {
    id: 106,
    title: "Lakeside Luxury Lodge",
    image: "Property4.png",
    size: 2874,
    rent: 2883.2,
    bedrooms: 4,
    bathrooms: 18,
    neighbourhood: "Brentwood",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 107,
    title: "Lakeside Tranquility Cottage",
    image: "Property6.png",
    size: 2678,
    rent: 2616.4,
    bedrooms: 4,
    bathrooms: 14,
    neighbourhood: "Chinatown",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 108,
    title: "Panoramic Peak View Chalet",
    image: "Property9.png",
    size: 1269,
    rent: 473.7,
    bedrooms: 12,
    bathrooms: 14,
    neighbourhood: "Forest Lawn",
    landlord: "testLandlord@email.com",
  },
  {
    id: 109,
    title: "Blissful Beach House",
    image: "Property1.png",
    size: 2663,
    rent: 2946.6,
    bedrooms: 14,
    bathrooms: 7,
    neighbourhood: "Discovery Ridge",
    landlord: "testLandlord@email.com",
  },
  {
    id: 110,
    title: "Sunset Splendor Villa",
    image: "Property9.png",
    size: 2852,
    rent: 225.1,
    bedrooms: 2,
    bathrooms: 16,
    neighbourhood: "Erlton",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 111,
    title: "Nature's Nest Hideaway",
    image: "Property5.png",
    size: 1827,
    rent: 366.9,
    bedrooms: 9,
    bathrooms: 1,
    neighbourhood: "Rosedale",
    landlord: "testLandlord@email.com",
  },
  {
    id: 112,
    title: "Sunset Splendor Villa",
    image: "Property7.png",
    size: 1467,
    rent: 878.5,
    bedrooms: 10,
    bathrooms: 9,
    neighbourhood: "Sunnyside",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 113,
    title: "Zen Garden Oasis",
    image: "Property4.png",
    size: 1457,
    rent: 506.7,
    bedrooms: 3,
    bathrooms: 9,
    neighbourhood: "Tuxedo Park",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 114,
    title: "City Lights Penthouse",
    image: "Property9.png",
    size: 979,
    rent: 1436.3,
    bedrooms: 12,
    bathrooms: 8,
    neighbourhood: "Haysboro",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 115,
    title: "Homestead Haven Hideout",
    image: "Property9.png",
    size: 919,
    rent: 1092.4,
    bedrooms: 3,
    bathrooms: 2,
    neighbourhood: "Crescent Heights",
    landlord: "testLandlord@email.com",
  },
  {
    id: 116,
    title: "Lakeside Tranquility Cottage",
    image: "Property6.png",
    size: 2509,
    rent: 1498.3,
    bedrooms: 13,
    bathrooms: 9,
    neighbourhood: "Christie Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 117,
    title: "Serene Cityscape Haven",
    image: "Property1.png",
    size: 1012,
    rent: 986.7,
    bedrooms: 8,
    bathrooms: 12,
    neighbourhood: "Erlton",
    landlord: "testLandlord@email.com",
  },
  {
    id: 118,
    title: "Lakeside Lodge Sanctuary",
    image: "Property4.png",
    size: 2814,
    rent: 3835.2,
    bedrooms: 10,
    bathrooms: 18,
    neighbourhood: "Beltline",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 119,
    title: "Panoramic Peak View Chalet",
    image: "Property1.png",
    size: 1819,
    rent: 1936.2,
    bedrooms: 3,
    bathrooms: 19,
    neighbourhood: "Mission",
    landlord: "testLandlord@email.com",
  },
  {
    id: 120,
    title: "Rustic Riverside Cabin",
    image: "Property6.png",
    size: 499,
    rent: 1892.4,
    bedrooms: 10,
    bathrooms: 8,
    neighbourhood: "Discovery Ridge",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 121,
    title: "Mountain Majesty Manor",
    image: "Property1.png",
    size: 1303,
    rent: 299.3,
    bedrooms: 0,
    bathrooms: 6,
    neighbourhood: "Christie Park",
    landlord: "testLandlord@email.com",
  },
  {
    id: 122,
    title: "Treehouse Retreat",
    image: "Property2.png",
    size: 1482,
    rent: 3743.2,
    bedrooms: 3,
    bathrooms: 8,
    neighbourhood: "Mission",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 123,
    title: "Lakeshore Luxury Villa",
    image: "Property3.png",
    size: 2518,
    rent: 2246.3,
    bedrooms: 11,
    bathrooms: 18,
    neighbourhood: "Capitol Hill",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 124,
    title: "Sunrise Spectacle Retreat",
    image: "Property8.png",
    size: 904,
    rent: 2066.6,
    bedrooms: 10,
    bathrooms: 10,
    neighbourhood: "Bankview",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 125,
    title: "Charming Cottage Escape",
    image: "Property4.png",
    size: 2765,
    rent: 2795.2,
    bedrooms: 14,
    bathrooms: 20,
    neighbourhood: "Cedarbrae",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 126,
    title: "Rustic Riverside Cabin",
    image: "Property4.png",
    size: 1418,
    rent: 829.9,
    bedrooms: 8,
    bathrooms: 13,
    neighbourhood: "Chinatown",
    landlord: "testLandlord@email.com",
  },
  {
    id: 127,
    title: "Tranquil Treetop Cabin",
    image: "Property1.png",
    size: 2158,
    rent: 3512.2,
    bedrooms: 8,
    bathrooms: 3,
    neighbourhood: "Erlton",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 128,
    title: "Stylish Skyline Suite",
    image: "Property5.png",
    size: 2188,
    rent: 2908.4,
    bedrooms: 7,
    bathrooms: 9,
    neighbourhood: "Mission",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 129,
    title: "Panoramic Peak View Chalet",
    image: "Property6.png",
    size: 953,
    rent: 398.2,
    bedrooms: 1,
    bathrooms: 14,
    neighbourhood: "Downtown",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 130,
    title: "Homestead Haven Hideout",
    image: "Property1.png",
    size: 2262,
    rent: 2092.0,
    bedrooms: 15,
    bathrooms: 12,
    neighbourhood: "Copperfield",
    landlord: "testLandlord@email.com",
  },
  {
    id: 131,
    title: "Sunset Splendor Villa",
    image: "Property1.png",
    size: 1489,
    rent: 3144.4,
    bedrooms: 13,
    bathrooms: 20,
    neighbourhood: "Glenbrook",
    landlord: "testLandlord@email.com",
  },
  {
    id: 132,
    title: "Lakeside Lodge Sanctuary",
    image: "Property9.png",
    size: 2225,
    rent: 3257.1,
    bedrooms: 4,
    bathrooms: 13,
    neighbourhood: "Edgemont",
    landlord: "testLandlord@email.com",
  },
  {
    id: 133,
    title: "Mountain View Hideaway",
    image: "Property7.png",
    size: 1585,
    rent: 1179.5,
    bedrooms: 12,
    bathrooms: 20,
    neighbourhood: "Copperfield",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 134,
    title: "Sunrise Spectacle Retreat",
    image: "Property5.png",
    size: 1906,
    rent: 3848.1,
    bedrooms: 3,
    bathrooms: 14,
    neighbourhood: "Greenview",
    landlord: "testLandlord@email.com",
  },
  {
    id: 135,
    title: "Homestead Haven Hideout",
    image: "Property9.png",
    size: 1941,
    rent: 1753.3,
    bedrooms: 3,
    bathrooms: 20,
    neighbourhood: "Evergreen",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 136,
    title: "Stylish Skyline Suite",
    image: "Property6.png",
    size: 802,
    rent: 2138.1,
    bedrooms: 4,
    bathrooms: 4,
    neighbourhood: "Copperfield",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 137,
    title: "Stylish Skyline Suite",
    image: "Property6.png",
    size: 2425,
    rent: 877.1,
    bedrooms: 6,
    bathrooms: 16,
    neighbourhood: "Elbow Park",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 138,
    title: "Moonlit Magic Manor",
    image: "Property7.png",
    size: 1472,
    rent: 1417.2,
    bedrooms: 3,
    bathrooms: 14,
    neighbourhood: "Rosedale",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 139,
    title: "Rustic Riverside Cabin",
    image: "Property6.png",
    size: 2338,
    rent: 2534.3,
    bedrooms: 8,
    bathrooms: 5,
    neighbourhood: "Elbow Park",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 140,
    title: "Mountain Majesty Manor",
    image: "Property8.png",
    size: 1099,
    rent: 1227.7,
    bedrooms: 4,
    bathrooms: 1,
    neighbourhood: "Coventry Hills",
    landlord: "testLandlord@email.com",
  },
  {
    id: 141,
    title: "Moonlit Magic Manor",
    image: "Property9.png",
    size: 2407,
    rent: 450.8,
    bedrooms: 8,
    bathrooms: 1,
    neighbourhood: "Rosedale",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 142,
    title: "Secluded Sanctuary Cottage",
    image: "Property2.png",
    size: 919,
    rent: 1647.2,
    bedrooms: 11,
    bathrooms: 11,
    neighbourhood: "Chinatown",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 143,
    title: "Sunset Splendor Villa",
    image: "Property2.png",
    size: 2429,
    rent: 3740.5,
    bedrooms: 5,
    bathrooms: 17,
    neighbourhood: "Dalhousie",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 144,
    title: "Mountain Majesty Manor",
    image: "Property5.png",
    size: 1712,
    rent: 3101.0,
    bedrooms: 12,
    bathrooms: 13,
    neighbourhood: "Discovery Ridge",
    landlord: "testLandlord3@email.com",
  },
  {
    id: 145,
    title: "Blissful Beach House",
    image: "Property5.png",
    size: 2651,
    rent: 219.6,
    bedrooms: 8,
    bathrooms: 14,
    neighbourhood: "Acadia",
    landlord: "testLandlord4@email.com",
  },
  {
    id: 146,
    title: "Coastal Paradise Cove",
    image: "Property8.png",
    size: 2486,
    rent: 1468.2,
    bedrooms: 6,
    bathrooms: 2,
    neighbourhood: "Collingwood",
    landlord: "testLandlord@email.com",
  },
  {
    id: 147,
    title: "Boho Beachfront Bungalow",
    image: "Property2.png",
    size: 414,
    rent: 3760.2,
    bedrooms: 12,
    bathrooms: 8,
    neighbourhood: "Coventry Hills",
    landlord: "testLandlord@email.com",
  },
  {
    id: 148,
    title: "Enchanting Garden Getaway",
    image: "Property6.png",
    size: 746,
    rent: 1028.5,
    bedrooms: 8,
    bathrooms: 6,
    neighbourhood: "Inglewood",
    landlord: "testLandlord2@email.com",
  },
  {
    id: 149,
    title: "Secret Garden Villa",
    image: "Property4.png",
    size: 2561,
    rent: 2423.9,
    bedrooms: 7,
    bathrooms: 12,
    neighbourhood: "Eagle Ridge",
    landlord: "testLandlord@email.com",
  },
  {
    id: 150,
    title: "Sunset Bliss Bungalow",
    image: "Property9.png",
    size: 990,
    rent: 905.8,
    bedrooms: 3,
    bathrooms: 9,
    neighbourhood: "Dover",
    landlord: "testLandlord4@email.com",
  },
];
export default propertyList;
