const propertyList=[
    {
        title: 'House on a Hill',
        image: 'Property1.png',
        size: '1200 sqft',
        rent: 899.99,
        bedrooms: 2,
        bathrooms: 1,
        neighbourhood: 'Downtown',
    },
    {
        title: 'Modern Downtown Loft',
        image: 'Property2.png',
        size: '1800 sqft',
        rent: 1099.99,
        bedrooms: 2,
        bathrooms: 2,
        neighbourhood: 'Downtown',
    },
    {
        title: 'Spacious Family Home',
        image: 'Property3.png',
        size: '2500 sqft',
        rent: 1399.99,
        bedrooms: 4,
        bathrooms: 3,
        neighbourhood: 'Downtown',
    },
    {
        title: 'Unique Hidden Home',
        image: 'Property4.png',
        size: '2000 sqft',
        rent: 899.99,
        bedrooms: 4,
        bathrooms: 3,
        neighbourhood: 'Downtown',
    },
    {
        title: 'Cozy Apartment',
        image: 'Property5.png',
        size: '1200 sqft',
        rent: 899.99,
        bedrooms: 2,
        bathrooms: 2,
        neighbourhood: 'Downtown',
    },
    {
        title: 'Suburban Home',
        image: 'Property4.png',
        size: '1800 sqft',
        rent: 1299.99,
        bedrooms: 4,
        bathrooms: 3,
        neighbourhood: 'Downtown',
    },
];
export default propertyList;